databases:
  - name: cinemania
    databaseName: cinemania
    user: charlettevibar
    plan: free

services:
  - type: web
    name: cinemania
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cinemania
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
